# Deep Fund Configuration
exp_name: "ablation_enhanced_memory"

# Trading settings
tickers:
  - TSLA
  - BTC


# Workflow execution mode
sequential_mode: false  # false for parallel, true for sequential execution

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - technical
  - company_news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "OpenAI"
  model: "gpt-4.1-nano" # DeepSeek-V3
  temperature: 0
