# DS@GT StockTron Configuration
exp_name: "enhanced_tools_tsla_btc"

# Trading settings
cashflow: 100000
tickers:
  - TSLA
  - BTC
portfolio_mode: market_timing # risk_managed (paper portfolio), market_timing (pure signal implementation)
enriched_memory: false # whether to consider past hit-rate in market_timing or not

# Workflow execution mode
sequential_mode: false  # false for parallel, true for sequential execution

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - company_news_enhanced
  - ml_model_online

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "OpenAI"
  model: "gpt-4.1-nano"
  temperature: 0
