# Deep Fund Configuration
exp_name: "dev_company_news_enhanced"

# Trading settings
cashflow: 100000
tickers:
  - TSLA
  - BTC


# Workflow execution mode
sequential_mode: false  # false for parallel, true for sequential execution

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - company_news_enhanced

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "OpenAI"
  model: "gpt-4o-mini" # DeepSeek-V3
