# Deep Fund Configuration
exp_name: "dev_tesla_baseline"

# Trading settings
cashflow: 100000
tickers:
  - TSLA


# Workflow execution mode
sequential_mode: false  # false for parallel, true for sequential execution

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  #- dummy
  - technical
  - company_news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "OpenAI"
  model: "gpt-4o-mini" # DeepSeek-V3
  temperature: 0
